apiVersion: byoh.miscord.win/v1alpha1
kind: BothInstallerConfigTemplate
metadata:
  labels:
    app.kubernetes.io/name: bothinstallerconfigtemplate
    app.kubernetes.io/instance: bothinstallerconfigtemplate-sample
    app.kubernetes.io/part-of: cluster-api-byoh-both
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: cluster-api-byoh-both
  name: bothinstallerconfigtemplate-sample
spec:
  # TODO(user): Add fields here
