apiVersion: byoh.miscord.win/v1alpha1
kind: BothInstallerConfig
metadata:
  labels:
    app.kubernetes.io/name: bothinstallerconfig
    app.kubernetes.io/instance: bothinstallerconfig-sample
    app.kubernetes.io/part-of: cluster-api-byoh-both
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: cluster-api-byoh-both
  name: bothinstallerconfig-sample
spec:
  # TODO(user): Add fields here
